import { Track } from "react-native-track-player";

export const playListData: Track [] = [


    { title: "Nanchaku", artist: "Seedhe Maut ft. MC Stan", album: "N", url: "audio/nanchaku.mp3", art: "images/n.png" },
    { title: "Hola Amigo", artist: "Kr$na ft. Seedhe Maut & Umair", album: "Single", url: "audio/hola-amigo.mp3", art: "images/hola-amigo-art.png" },
    { title: "Kodak", artist: "King ft. Seedhe Maut", album: "Monopoly Moves", url: "audio/kodak.mp3", art: "images/kodak-art.png" },
    { title: "Maina", artist: "Seedhe Maut", album: "Nayaab", url: "audio/maina.mp3", art: "images/maina-art.png" },
    { title: "Tour Shit", artist: "Seedhe Maut", album: "Single", url: "audio/tour_shit.mp3", art: "images/tour_shit-art.png" },
    { title: "TT", artist: "Seedhe Maut", album: "Single", url: "audio/tt.mp3", art: "images/tt-art.png" },
    { title: "Shutdown", artist: "Seedhe Maut", album: "Single", url: "audio/shutdown.mp3", art: "images/shutdown-art.png" },
    { title: "Kaanch Ke Ghar", artist: "Seedhe Maut", album: "Single", url: "audio/kaanch_ke_ghar.mp3", art: "images/kaanch_ke_ghar-art.png" },
    { title: "Bure Din", artist: "Seedhe Maut ft. Mick Jenkins", album: "Single", url: "audio/bure_din.mp3", art: "images/bure_din-art.png" },
    { title: "Nalla Freestyle", artist: "Seedhe Maut & DJ SA", album: "Single", url: "audio/nfs.mp3", art: "images/nfs-art.png" },
    { title: "Bajenge", artist: "Seedhe Maut ft. Baadshah", album: "Single", url: "audio/bajenge.mp3", art: "images/bajenge-art.png" },
    { title: "Akatsuki", artist: "Seedhe Maut ft. Raga", album: "Lunch Break", url: "audio/akatsuki.mp3", art: "images/lunch-break.png" },
    { title: "Asal G", artist: "Seedhe Maut ft. Faris Shafi & Talal Qureshi", album: "Lunch Break", url: "audio/asal-g.mp3", art: "images/lunch-break.png" },
    { title: "Focus Sedated", artist: "Seedhe Maut", album: "Lunch Break", url: "audio/focus-sedated.mp3", art: "images/lunch-break.png" },
    { title: "I don't miss that life", artist: "Seedhe Maut", album: "Lunch Break", url: "audio/idmtl.mp3", art: "images/lunch-break.png" },
    { title: "Joint in the booth", artist: "Seedhe Maut", album: "Lunch Break", url: "audio/jitb.mp3", art: "images/lunch-break.png" },
    { title: "Khatta flow", artist: "Seedhe Maut ft. KR$NA", album: "Lunch Break", url: "audio/khatta-flow.mp3", art: "images/lunch-break.png" },
    { title: "Kavi", artist: "Seedhe Maut", album: "Lunch Break", url: "audio/kavi.mp3", art: "images/lunch-break.png" },
    { title: "Kavi kehna chahte hain...", artist: "Seedhe Maut", album: "Lunch Break", url: "audio/kkch.mp3", art: "images/lunch-break.png" },
    { title: "Lunch break", artist: "Seedhe Maut", album: "Lunch Break", url: "audio/lunchbreak.mp3", art: "images/lunch-break.png" },
    { title: "Naam Kaam Seher", artist: "Seedhe Maut ft.Qaab & Rebel", album: "Lunch Break", url: "audio/namkamseher.mp3", art: "images/lunch-break.png" },
    { title: "Pain", artist: "Seedhe Maut", album: "Lunch Break", url: "audio/pain.mp3", art: "images/lunch-break.png" },
    { title: "Swah!", artist: "Seedhe Maut ft.Baadshah", album: "Lunch Break", url: "audio/swah.mp3", art: "images/lunch-break.png" },
    { title: "W", artist: "Seedhe Maut", album: "Lunch Break", url: "audio/w.mp3", art: "images/lunch-break.png" },
    { title: "Khush Nahi", artist: "Seedhe Maut", album: "Shakti", url: "audio/khushnahi.mp3", art: "images/shakti-art.webp" },
    { title: "Soyi Nahi", artist: "Seedhe Maut", album: "Shakti", url: "audio/soyinahi.mp3", art: "images/shakti-art.webp" },
    { title: "Naksha", artist: "Seedhe Maut", album: "Shakti", url: "audio/naksha.mp3", art: "images/shakti-art.webp" },
    { title: "Raat ki rani", artist: "Seedhe Maut", album: "Shakti", url: "audio/rkr.mp3", art: "images/shakti-art.webp" },
    { title: "101", artist: "Seedhe Maut", album: "Single", url: "audio/101.mp3", art: "images/101.png" },
    { title: "Teen dost", artist: "Seedhe Maut & Sez on the beat", album: "Nayaab", url: "audio/3dost.mp3", art: "images/nayaab.png" },
    { title: "Chidiya udd", artist: "Seedhe Maut & Sez on the beat", album: "Nayaab", url: "audio/chidiya.mp3", art: "images/nayaab.png" },
    { title: "Do guna", artist: "Seedhe Maut", album: "Single", url: "audio/doguna.mp3", art: "images/doguna.png" },
    { title: "11k", artist: "Seedhe Maut", album: "Lunch Break", url: "audio/11k.mp3", art: "images/lunch-break.png" },
    { title: "Gandi Aulaad", artist: "Seedhe Maut & Sez on the beat", album: "Nayaab", url: "audio/ga.mp3", art: "images/nayaab.png" },
    { title: "Roshni", artist: "Sickflip, Ritviz, Seedhe maut", album: "Nayaab", url: "audio/roshni.mp3", art: "images/roshni.png" },
    { title: "Shayaar", artist: "Bharat chauhan & Seedhe maut", album: "Single", url: "audio/shaayar.mp3", art: "images/shayaar.png" },
    { title: "Namastute", artist: "Seedhe Maut", album: "N", url: "audio/namastute.mp3", art: "images/n.png" },

]
