import { Track } from 'react-native-track-player'; 

export const playListData: Track[] = [
    { id: 1, title: 'Nanchaku', artist: 'Seedhe Maut ft. MC Stan', album: 'N', url: 'audio/nanchaku.mp3', art: 'images/n.png' },
    { id: 2, title: 'Hola Amigo', artist: 'Kr$na ft. Seedhe Maut & Umair', album: 'Single', url: 'audio/hola-amigo.mp3', art: 'images/hola-amigo-art.png' },
    { id: 3, title: 'Kodak', artist: 'King ft. Seedhe Maut', album: 'Monopoly Moves', url: 'audio/kodak.mp3', art: 'images/kodak-art.png' },
    { id: 4, title: 'Maina', artist: 'Seedhe Maut', album: 'Nayaab', url: 'audio/maina.mp3', art: 'images/maina-art.png' },
    { id: 5, title: 'Tour Shit', artist: 'Seedhe Maut', album: 'Single', url: 'audio/tour_shit.mp3', art: 'images/tour_shit-art.png' },
    { id: 6, title: 'TT', artist: 'Seedhe Maut', album: 'Single', url: 'audio/tt.mp3', art: 'images/tt-art.png' },
    { id: 7, title: 'Shutdown', artist: 'Seedhe Maut', album: 'Single', url: 'audio/shutdown.mp3', art: 'images/shutdown-art.png' },
    { id: 8, title: 'Kaanch Ke Ghar', artist: 'Seedhe Maut', album: 'Single', url: 'audio/kaanch_ke_ghar.mp3', art: 'images/kaanch_ke_ghar-art.png' },
    { id: 9, title: 'Bure Din', artist: 'Seedhe Maut ft. Mick Jenkins', album: 'Single', url: 'audio/bure_din.mp3', art: 'images/bure_din-art.png' },
    { id: 10, title: 'Nalla Freestyle', artist: 'Seedhe Maut & DJ SA', album: 'Single', url: 'audio/nfs.mp3', art: 'images/nfs-art.png' },
    { id: 11, title: 'Bajenge', artist: 'Seedhe Maut ft. Baadshah', album: 'Single', url: 'audio/bajenge.mp3', art: 'images/bajenge-art.png' },
    { id: 12, title: 'Akatsuki', artist: 'Seedhe Maut ft. Raga', album: 'Lunch Break', url: 'audio/akatsuki.mp3', art: 'images/lunch-break.png' },
    { id: 13, title: 'Asal G', artist: 'Seedhe Maut ft. Faris Shafi & Talal Qureshi', album: 'Lunch Break', url: 'audio/asal-g.mp3', art: 'images/lunch-break.png' },
    { id: 14, title: 'Focus Sedated', artist: 'Seedhe Maut', album: 'Lunch Break', url: 'audio/focus-sedated.mp3', art: 'images/lunch-break.png' },
     { id: 15, title: 'I don\'t miss that life', artist: 'Seedhe Maut', album: 'Lunch Break', url: 'audio/idmtl.mp3', art: 'images/lunch-break.png' },
    { id: 16, title: 'Joint in the booth', artist: 'Seedhe Maut', album: 'Lunch Break', url: 'audio/jitb.mp3', art: 'images/lunch-break.png' },
    { id: 17, title: 'Khatta flow', artist: 'Seedhe Maut ft. KR$NA', album: 'Lunch Break', url: 'audio/khatta-flow.mp3', art: 'images/lunch-break.png' },
    { id: 18, title: 'Kavi', artist: 'Seedhe Maut', album: 'Lunch Break', url: 'audio/kavi.mp3', art: 'images/lunch-break.png' },
    { id: 19, title: 'Kavi kehna chahte hain...', artist: 'Seedhe Maut', album: 'Lunch Break', url: 'audio/kkch.mp3', art: 'images/lunch-break.png' },
    { id: 20, title: 'Lunch break', artist: 'Seedhe Maut', album: 'Lunch Break', url: 'audio/lunchbreak.mp3', art: 'images/lunch-break.png' },
    { id: 21, title: 'Naam Kaam Seher', artist: 'Seedhe Maut ft.Qaab & Rebel', album: 'Lunch Break', url: 'audio/namkamseher.mp3', art: 'images/lunch-break.png' },
    { id: 22, title: 'Pain', artist: 'Seedhe Maut', album: 'Lunch Break', url: 'audio/pain.mp3', art: 'images/lunch-break.png' },
    { id: 23, title: 'Swah!', artist: 'Seedhe Maut ft.Baadshah', album: 'Lunch Break', url: 'audio/swah.mp3', art: 'images/lunch-break.png' },
    { id: 24, title: 'W', artist: 'Seedhe Maut', album: 'Lunch Break', url: 'audio/w.mp3', art: 'images/lunch-break.png' },
    { id: 25, title: 'Khush Nahi', artist: 'Seedhe Maut', album: 'Shakti', url: 'audio/khushnahi.mp3', art: 'images/shakti-art.webp' },
    { id: 26, title: 'Soyi Nahi', artist: 'Seedhe Maut', album: 'Shakti', url: 'audio/soyinahi.mp3', art: 'images/shakti-art.webp' },
    { id: 27, title: 'Naksha', artist: 'Seedhe Maut', album: 'Shakti', url: 'audio/naksha.mp3', art: 'images/shakti-art.webp' },
    { id: 28, title: 'Raat ki rani', artist: 'Seedhe Maut', album: 'Shakti', url: 'audio/rkr.mp3', art: 'images/shakti-art.webp' },
    { id: 29, title: '101', artist: 'Seedhe Maut', album: 'Single', url: 'audio/101.mp3', art: 'images/101.png' },
    { id: 30, title: 'Teen dost', artist: 'Seedhe Maut & Sez on the beat', album: 'Nayaab', url: 'audio/3dost.mp3', art: 'images/nayaab.png' },
    { id: 31, title: 'Chidiya udd', artist: 'Seedhe Maut & Sez on the beat', album: 'Nayaab', url: 'audio/chidiya.mp3', art: 'images/nayaab.png' },
    { id: 32, title: 'Do guna', artist: 'Seedhe Maut', album: 'Single', url: 'audio/doguna.mp3', art: 'images/doguna.png' },
    { id: 33, title: '11k', artist: 'Seedhe Maut', album: 'Lunch Break', url: 'audio/11k.mp3', art: 'images/lunch-break.png' },
    { id: 34, title: 'Gandi Aulaad', artist: 'Seedhe Maut & Sez on the beat', album: 'Nayaab', url: 'audio/ga.mp3', art: 'images/nayaab.png' },
    { id: 35, title: 'Roshni', artist: 'Sickflip, Ritviz, Seedhe maut', album: 'Nayaab', url: 'audio/roshni.mp3', art: 'images/roshni.png' },
    { id: 36, title: 'Shayaar', artist: 'Bharat chauhan & Seedhe maut', album: 'Single', url: 'audio/shaayar.mp3', art: 'images/shayaar.png' },
    { id: 37, title: 'Namastute', artist: 'Seedhe Maut', album: 'N', url: 'audio/namastute.mp3', art: 'images/n.png' },
]
